package com.ez.entity;

import lombok.*;
import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.Min;

@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@Entity
@Table(name = "fileStorage")
public class FileStorage {

    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Min(value = 1, message = "Value of id must be greater than or equal to 1")
    private Long id;

    // customFilename = timestamp + UUID + extension(ex: .jpg)
    // ex: customFilename = "20230405143231_3ed7c8ea-114e-4c1f-a3d3-8e5a439e9aff.jpg"
    private String customFilename;

    // original filename which user uploaded to the system
    // ex: "abc.txt", "xyz.jpg"
    private String originalFilename;

    // ex: "image/jpeg", "application/x-7z-compressed",...
    private String fileType;

    public FileStorage(String customFilename, String originalFilename, String fileType) {

        this.customFilename = customFilename;
        this.originalFilename = originalFilename;
        this.fileType = fileType;

    }

}
