package com.ez.entity;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@Entity
@Table(name = "calendar")
// HDCalendar(Help Desk Calendar) class.
// note: do use the 'Calendar' class.
// Because this class(Calendar) is a standard class of the Java(java.util.Calendar)
public class HDCalendar {

    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Min(value = 1, message = "Value of id must be greater than or equal to 1")
    private Long id;

    // calendar name
    @Size(min = 1, max = 50, message = "Length of the calendar name must be between 1 and 50 characters")
    private String name;

    @Pattern(regexp = "Active|Inactive", message = "Value of the status must be 'Active' or 'Inactive'")
    private String status;

    public HDCalendar(String name, String status) {

        this.name = name;
        this.status = status;

    }
}
