package com.ez.entity;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.*;

@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@Entity
// use this class Team(entity) is for save "team"(without supporters) into database
// via TeamRepository
public class Team {

    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Min(value = 1, message = "Value of id must be greater than or equal to 1")
    private Long id;

    @Size(min = 1, max = 50, message = "Length of the team name must be between 1 and 50 characters")
    private String name;

    @Pattern(regexp = "A|M", message = "Value of the assignment method must be 'A' or 'M'")
    private String assignmentMethod;

//    @Min(value = 1, message = "Value of calendarid must be greater than or equal to 1")
//    private long calendarid;

    @Pattern(regexp = "Active|Inactive", message = "Value of the status must be 'Active' or 'Inactive'")
    private String status;

    //    public Team(String name, String assignmentMethod, long calendarid, String status) {
    public Team(String name, String assignmentMethod, String status) {

        this.name = name;
        this.assignmentMethod = assignmentMethod;
//        this.calendarid = calendarid;
        this.status = status;

    }

}
