package com.ez.entity;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.*;
import java.io.Serializable;
import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@Entity
public class Ticket implements Serializable {

    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Min(value = 1, message = "Value of id must be greater than or equal to 1")
    private Long ticketid;

    @Size(min = 1, message = "Please input the subject")
    private String subject;

    @Min(value = 1, message = "Value of category id must be greater than or equal to 1")
    private long categoryid;

    @Min(value = 1, message = "Value of creator id must be greater than or equal to 1")
    private long creatorid;

    @Min(value = 1, message = "Value of team id must be greater than or equal to 1")
    private long teamid;

    @Min(value = 1, message = "Value of priority id must be greater than or equal to 1")
    private long priorityid;

    //    @Min(value = 1, message = "Value of assignee id must be greater than or equal to 1")
    private long assigneeid;

    @Pattern(regexp = "^[1-5]", message = "Value of the ticket status must be 1 of 5 following values: Open, Assigned, Resolved, Closed, Cancel")
    private long ticketStatusid;

    @Size(min = 1, message = "Please input the content")
    private String content;

//    @Size(min = 1, message = "Please input the content")
    private String fileUrl;

    @CreationTimestamp
    private Date createDatetime;

    @UpdateTimestamp
    private Date lastUpdateDatetime;



//
//    //    public Team(String name, String assignmentMethod, long calendarid, String status) {
//    public Team(String name, String assignmentMethod, String status) {
//
//        this.name = name;
//        this.assignmentMethod = assignmentMethod;
////        this.calendarid = calendarid;
//        this.status = status;
//
//    }
}
